version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgres/data

  backend:
    image: nkoles/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
    - db

  frontend:
    env_file: .env
    image: nkoles/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
      

  gateway:
    image: nkoles/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend